---
- name: Include RHEL fact-gathering
  ansible.builtin.import_tasks: rhel.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: Include Windows fact-gathering
  ansible.builtin.import_tasks: windows.yml
  when: ansible_facts['os_family'] == 'Windows'

- name: Evaluate baseline checks
  ansible.builtin.import_tasks: checks.yml

- name: Render report and gate on compliance
  ansible.builtin.import_tasks: report.yml
