---
- name: Derive root filesystem size in GB
  ansible.builtin.set_fact:
    root_fs_size_gb: >-
      {{
        (ansible_facts['mounts']
          | selectattr('mount', 'equalto', '/')
          | map(attribute='size_total')
          | first
          | int / 1073741824
        ) | round(1)
      }}

- name: Gather SSH security facts
  ansible.builtin.import_tasks: gather_ssh_facts.yml
  when: baseline_security_checks_enabled | bool
