---
galaxy_info:
  author: mlowcher61
  description: Validates a RHEL or Windows host against a technical baseline
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - baseline
    - compliance
    - rhel
    - windows
dependencies: []
